/*
<<<<<<< HEAD:apis/config/v1/doc.go
Copyright 2022 The Kubernetes Authors.
=======
Copyright The Kubernetes Authors.
>>>>>>> add folders:pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/generated_expansion.go

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

<<<<<<< HEAD:apis/config/v1/doc.go
// +k8s:deepcopy-gen=package
// +k8s:conversion-gen=sigs.k8s.io/scheduler-plugins/apis/config
// +k8s:defaulter-gen=TypeMeta
// +k8s:defaulter-gen-input=sigs.k8s.io/scheduler-plugins/apis/config/v1
=======
// Code generated by client-gen. DO NOT EDIT.
>>>>>>> add folders:pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/generated_expansion.go

package v1alpha1

<<<<<<< HEAD:apis/config/v1/doc.go
// Package v1 is the v1 version of the API.
package v1 // import "sigs.k8s.io/scheduler-plugins/apis/config/v1"
=======
type ElasticQuotaExpansion interface{}

type PodGroupExpansion interface{}
>>>>>>> add folders:pkg/generated/clientset/versioned/typed/scheduling/v1alpha1/generated_expansion.go
