apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  # kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
- schedulerName: diskio-aware-scheduler
  plugins:
    multiPoint:
      enabled:
      - name: DiskIOAware
  pluginConfig:
  - name: DiskIOAware
    args:
      # other strategies are MostAllocated
      scoringStrategy: "LeastAllocated"
      nsWhiteList: 
      - kube-system
      - ioi-system
      - kube-system
      - kube-flannel
      - calico-apiserver
      - calico-system
      - tigera-operator


      
